baseurl: "/cadmium-tests" # the subpath of your site, e.g. /blog/
url: "https://southworkscom.github.io" # the base hostname & protocol for your site

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
